### ISSUE TITLE
Need Sync Progress displayed after "Start"

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/GordianServer-macOS#53]
(using PR #52)

After pressing "Start", the indicator for Mainnet show as green that it has started.

However, the "synced?" button-like indicator is gray and isn't showing any progress. There should be an active indicator %, checked regularly and displayed here until Gordian Server app sees that the sync is complete, showing % progress for complete, like that for FN1 or Gordian Wallet.

Refresh should not be required, especially the first time.

Bitcoin-Core UX show that progress, we should to.

**Comment by Fonta1n3** [comment]
Sure thing, but it will not be instant, the data does refresh when you tap start currently, the issue is just as in Bitcoin-Qt you will need to wait until it finishes "loading blocks..." before you can access any information via `rpc`, there will always be a significant delay (30 seconds or so) after tapping "Start" before we can fetch data.

In Bitcoin-Qt they handle this by showing a "loading blocks..." view before you can access the GUI if I remember correctly. We could do the same.

**Comment by Fonta1n3** [comment]
@ChristopherA https://github.com/BlockchainCommons/GordianServer-macOS/pull/52/commits/991ae7f3fc6d49d0eb0cafdf119c75034791025b fixes this.
